# Generated by Django 4.2.17 on 2024-12-05 13:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('subjects', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='subject',
            options={'ordering': ['-created_at']},
        ),
    ]
