# Generated by Django 4.2.17 on 2024-12-05 14:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('subjects', '0002_alter_subject_options'),
    ]

    operations = [
        migrations.AlterField(
            model_name='subject',
            name='type',
            field=models.SmallIntegerField(choices=[(0, 'Umum'), (1, 'Jurusan'), (2, 'Ekstrakurikuler')], default=0),
        ),
    ]
